function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.11 (R2021b) and Automated Driving Toolbox 3.4 (R2021b).
% Generated on: 27-Feb-2024 11:35:04

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [0.3 0 0;
    100.1 0 0];
laneSpecification = lanespec(2, 'Width', 4);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [4.7 -2.2 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [4.7 -2 0;
    13.6 -1.4 0;
    17.3 -1.2 0;
    23.7 0.4 0;
    28.5 1.7 0;
    31.3 2.2 0;
    36.6 2.8 0;
    40.1 3.3 0;
    53.1 2.6 0;
    61.1 3 0;
    71.9 2.6 0;
    83.6 1.8 0;
    91.6 2 0];
speed = [15;15;15;15;15;15;15;15;15;15;15;15;15];
trajectory(egoVehicle, waypoints, speed);

